# Generated by Django 2.2.12 on 2022-09-09 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_follow_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='postId',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='postId',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='userId',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='userId',
        ),
    ]
