# Generated by Django 2.2.12 on 2022-10-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20220927_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='empty.jpg', max_length=700, null=True, upload_to=''),
        ),
    ]
