# Generated by Django 2.2.12 on 2022-10-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20221005_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='empty.jpg', max_length=700, null=True, upload_to=''),
        ),
    ]
